# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('estimate', models.CharField(max_length=255)),
                ('precondition', models.TextField(blank=True)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.Priority')),
            ],
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.ProjectStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('testProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestProject')),
            ],
        ),
        migrations.CreateModel(
            name='TestRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('trrDate', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.StatusTestRun')),
            ],
        ),
        migrations.CreateModel(
            name='TestRunTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestCase')),
                ('testRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestRun')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestProject')),
            ],
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='testrunTestcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestRunTestCase'),
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrun',
            name='testcases',
            field=models.ManyToManyField(through='diplom.TestRunTestCase', to='diplom.TestCase'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testSuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestSuit'),
        ),
    ]
