# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0002_auto_20170417_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='TestRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('trrDATE', models.DateTimeField()),
                ('statusTestCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.StatusTestCase')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestCase')),
            ],
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.ProjectStatus'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=90),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='testRun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.TestRun'),
        ),
        migrations.AddField(
            model_name='testrunresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.User'),
        ),
    ]
