# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0003_auto_20170418_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
