# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0004_testcase_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='precondition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
