# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0005_auto_20170418_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='precondition',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuit',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
