# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0006_auto_20170418_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='testcases',
            field=models.ManyToManyField(to='diplom.TestCase'),
        ),
    ]
